### ISSUE TITLE
Eliminating "items" in URLs

### ISSUE THREAD

**Issue by lebleucleu** [bwein-net/contao-gallery#2]
Thanks for your helpful extension!

In my case it generates URLs like _example.org/werke/items/neue-galerie.html_
I would prefer URLs like _example.org/werke/neue-galerie.html_

The Contao setting "Auto_item" eliminates "items" automatically as far as i know and it is activated in Contao 5.3 by default. 
Is it possible to have URLs without "items"?

**Comment by rabauss** [comment]
This might be a bug with contao 5.3 because I haven't fully tested the extension with contao 5.3.
I will check that in the next days.

Obviously, it needs to be refactored to `ContentUrlGenerator` and eliminate the config check for auto item here: https://github.com/bwein-net/contao-gallery/blob/4e722f37ffb1fcf22a8286e56692900bb4d12ec7/src/Renderer/GalleryUrlRenderer.php#L64

**Comment by rabauss** [comment]
Please take a look at the new release 2.0 - the problem should be fixed

**Comment by lebleucleu** [comment]
Thank you for the new release!
Unfortunately Contao Manager still shows version 1.0.1 of Contao-Gallery. And when you click the "Details"-button in the manager, the extension doesn't load.

**Comment by rabauss** [comment]
@lebleucleu your error seems to be related with your contao manager because in the extension list everything is fine: https://extensions.contao.org/?p=bwein-net%2Fcontao-gallery
I just removed the compatiblity for contao 4.13 in version 2, which is only compatible for contao 5 with symfony 6!
